const colors = {
  text: "#412f20",
  background: "#fffaf0",
  primary: "#ff1616",
  secondary: "#ffde59",
};

export default {
  space: [
    "0rem",
    "0.25rem",
    "0.5rem",
    "1rem",
    "2rem",
    "4rem",
    "8rem",
    "16rem",
    "32rem",
    "64rem",
  ],
  sizes: {
    body: "50ch",
    heading: "20ch",
  },
  fonts: {
    body:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    heading: "inherit",
    monospace: "Menlo, monospace",
  },
  fontSizes: [
    "0.512rem",
    "0.64rem",
    "0.8rem",
    "1rem",
    "1.25rem",
    "1.563rem",
    "1.953rem",
    "2.441rem",
    "3.052rem",
  ],
  fontWeights: {
    body: 400,
    heading: 900,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  colors: colors,
  container: {
    marginTop: "8vw",
    marginBottom: "8vw",
    marginLeft: "10vw",
    maxWidth: "calc(100vw - 25vw)",
  },
  styles: {
    root: {
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
      fontSize: "125%",
    },
    h1: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      maxWidth: "heading",
      fontSize: 7,
      letterSpacing: "0.035em",
      "&:first-child": {
        "-webkit-text-fill-color": colors.secondary,
        "-webkit-text-stroke-width": "0.035em",
        "-webkit-text-stroke-color": colors.primary,
        fontSize: 8,
        marginBottom: 4,
      },
    },
    h2: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      maxWidth: "heading",
      fontSize: 6,
      marginTop: 5,
    },
    h3: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      maxWidth: "heading",
      fontSize: 5,
    },
    h4: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      maxWidth: "heading",
      fontSize: 4,
    },
    h5: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      maxWidth: "heading",
      fontSize: 3,
    },
    h6: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      maxWidth: "heading",
      fontSize: 2,
    },
    p: {
      color: "text",
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
      maxWidth: "body",
    },
    a: {
      color: "primary",
    },
    pre: {
      fontFamily: "monospace",
      overflowX: "auto",
      code: {
        color: "inherit",
      },
    },
    code: {
      fontFamily: "monospace",
      fontSize: "inherit",
    },
    table: {
      width: "100%",
      borderCollapse: "separate",
      borderSpacing: 0,
    },
    th: {
      textAlign: "left",
      borderBottomStyle: "solid",
    },
    td: {
      textAlign: "left",
      borderBottomStyle: "solid",
    },
    img: {
      maxWidth: "100%",
      marginTop: 3,
      marginBottom: 3,
    },
    hr: {
      borderTop: "4px solid",
      borderColor: "secondary",
      opacity: "0.7",
      marginTop: 5,
      marginBottom: 5,
    },
    ".gatsby-resp-iframe-wrapper": {
      maxWidth: "100%",
      borderStyle: "solid",
      borderWidth: "2vw",
      borderColor: "secondary",
      borderRadius: "0.5vw",
      marginTop: 4,
      marginBottom: 4,
      marginLeft: "-1.5vw",
      marginRight: "-1.5vw",
    },
  },
};
